/*
 * File Storage API
 *
 * A REST API for uploading and managing files using UploadThing
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type InlineResponse200 struct {
	Files []UploadedFile `json:"files,omitempty"`
}
