/*
 * File Storage API
 *
 * A REST API for uploading and managing files using UploadThing
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type UploadedFile struct {
	// Unique file identifier
	Id string `json:"id"`
	// Original filename
	Name string `json:"name"`
	// Public URL to access the file
	Url string `json:"url"`
}
