/*
 * File Storage API
 *
 * A REST API for uploading and managing files using UploadThing
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type DeleteRequest struct {
	// Array of file IDs to delete
	FileIds []string `json:"fileIds"`
}
