definitions:
  handlers.ErrorResp:
    properties:
      error:
        type: string
    type: object
  handlers.JWK:
    properties:
      alg:
        type: string
      e:
        type: string
      kid:
        type: string
      kty:
        type: string
      "n":
        type: string
      use:
        type: string
    type: object
  handlers.JWKS:
    properties:
      keys:
        items:
          $ref: '#/definitions/handlers.JWK'
        type: array
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: ichibuy-auth.vercel.app
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is the ichibuy/auth API.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: ichibuy/auth API
  version: "1.0"
paths:
  /api/v1/auth/.well-known/jwks.json:
    get:
      consumes:
      - application/json
      description: Returns JSON Web Key Set for JWT verification
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.JWKS'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResp'
      summary: GetJWKS
  /api/v1/auth/{provider}:
    get:
      consumes:
      - application/json
      description: StartOAuth
      produces:
      - application/json
      responses:
        "307":
          description: Temporary Redirect
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResp'
      summary: StartOAuth
  /api/v1/auth/{provider}/callback:
    get:
      consumes:
      - application/json
      description: OAuthCallback
      produces:
      - application/json
      responses:
        "307":
          description: Temporary Redirect
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrorResp'
      summary: OAuthCallback
swagger: "2.0"
