basePath: /api/v1
definitions:
  handlers.ErrorResp:
    properties:
      error:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is the ichibuy/auth API.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: ichibuy/auth API
  version: "1.0"
paths:
  /api/v1/auth/.well-known/jwks.json:
    get:
      consumes:
      - application/json
      description: GetJWKS
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrorResp'
      summary: GetJWKS
  /api/v1/auth/{provider}:
    get:
      consumes:
      - application/json
      description: StartOAuth
      produces:
      - application/json
      responses:
        "307":
          description: Temporary Redirect
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResp'
      summary: StartOAuth
  /api/v1/auth/{provider}/callback:
    get:
      consumes:
      - application/json
      description: OAuthCallback
      produces:
      - application/json
      responses:
        "307":
          description: Temporary Redirect
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrorResp'
      summary: OAuthCallback
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
