---
swagger: "2.0"
info:
  description: "A REST API for uploading and managing files using UploadThing"
  version: "1.0.0"
  title: "File Storage API"
  contact:
    name: "API Support"
host: "localhost:3000"
basePath: "/api/v1"
tags:
- name: "Files"
  description: "File upload and management operations"
- name: "Health"
  description: "API health check"
schemes:
- "http"
- "https"
consumes:
- "multipart/form-data"
- "application/json"
produces:
- "application/json"
paths:
  /files/upload:
    post:
      tags:
      - "Files"
      summary: "Upload multiple files"
      description: "Upload one or more files to UploadThing storage with a specified\
        \ domain"
      consumes:
      - "multipart/form-data"
      parameters:
      - name: "files"
        in: "formData"
        description: "Files to upload"
        required: true
        type: "file"
        collectionFormat: "multi"
        x-exportParamName: "Files"
      - name: "domain"
        in: "formData"
        description: "Domain for all uploaded files"
        required: true
        type: "string"
        x-exportParamName: "Domain"
      responses:
        "200":
          description: "Files uploaded successfully"
          schema:
            $ref: "#/definitions/inline_response_200"
        "400":
          description: "Bad request - missing files or domain"
          schema:
            $ref: "#/definitions/Error"
        "500":
          description: "Internal server error"
          schema:
            $ref: "#/definitions/Error"
  /files/delete:
    delete:
      tags:
      - "Files"
      summary: "Delete multiple files"
      description: "Delete multiple files by their IDs from UploadThing storage"
      consumes:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "File IDs to delete"
        required: true
        schema:
          $ref: "#/definitions/DeleteRequest"
        x-exportParamName: "Body"
      responses:
        "204":
          description: "Files deleted successfully"
        "400":
          description: "Bad request - missing or invalid file IDs"
          schema:
            $ref: "#/definitions/Error"
        "500":
          description: "Internal server error"
          schema:
            $ref: "#/definitions/Error"
definitions:
  UploadedFile:
    type: "object"
    required:
    - "id"
    - "name"
    - "url"
    properties:
      id:
        type: "string"
        example: "abc123def456"
        description: "Unique file identifier"
      name:
        type: "string"
        example: "document.pdf"
        description: "Original filename"
      url:
        type: "string"
        example: "https://uploadthing.com/f/abc123def456"
        description: "Public URL to access the file"
    example:
      name: "document.pdf"
      id: "abc123def456"
      url: "https://uploadthing.com/f/abc123def456"
  DeleteRequest:
    type: "object"
    required:
    - "fileIds"
    properties:
      fileIds:
        type: "array"
        example:
        - "abc123def456"
        - "xyz789ghi012"
        description: "Array of file IDs to delete"
        items:
          type: "string"
    example:
      fileIds:
      - "abc123def456"
      - "xyz789ghi012"
  Error:
    type: "object"
    required:
    - "error"
    properties:
      error:
        type: "string"
        example: "Files array is required and cannot be empty"
        description: "Error message"
  inline_response_200:
    type: "object"
    properties:
      files:
        type: "array"
        items:
          $ref: "#/definitions/UploadedFile"
    example:
      files:
      - name: "document.pdf"
        id: "abc123def456"
        url: "https://uploadthing.com/f/abc123def456"
      - name: "document.pdf"
        id: "abc123def456"
        url: "https://uploadthing.com/f/abc123def456"
