---
swagger: "2.0"
info:
  description: "This is the ichibuy/auth API."
  version: "1.0"
  title: "ichibuy/auth API"
  termsOfService: "http://swagger.io/terms/"
  contact:
    name: "API Support"
    url: "http://www.swagger.io/support"
    email: "support@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "ichibuy-auth.vercel.app"
paths:
  /api/v1/auth/.well-known/jwks.json:
    get:
      summary: "GetJWKS"
      description: "Returns JSON Web Key Set for JWT verification"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/handlers.JWKS"
        "500":
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/handlers.ErrorResp"
  /api/v1/auth/{provider}:
    get:
      summary: "StartOAuth"
      description: "StartOAuth"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "provider"
        in: "path"
        description: "Provider: google"
        required: true
        type: "string"
        x-exportParamName: "Provider"
      responses:
        "307":
          description: "Temporary Redirect"
        "500":
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/handlers.ErrorResp"
  /api/v1/auth/{provider}/callback:
    get:
      summary: "OAuthCallback"
      description: "OAuthCallback"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "provider"
        in: "path"
        description: "Provider: google"
        required: true
        type: "string"
        x-exportParamName: "Provider"
      responses:
        "307":
          description: "Temporary Redirect"
        "400":
          description: "Bad Request"
          schema:
            $ref: "#/definitions/handlers.ErrorResp"
definitions:
  handlers.ErrorResp:
    type: "object"
    properties:
      error:
        type: "string"
  handlers.JWK:
    type: "object"
    properties:
      alg:
        type: "string"
      e:
        type: "string"
      kid:
        type: "string"
      kty:
        type: "string"
      "n":
        type: "string"
      use:
        type: "string"
    example:
      kty: "kty"
      e: "e"
      use: "use"
      kid: "kid"
      alg: "alg"
      "n": "n"
  handlers.JWKS:
    type: "object"
    properties:
      keys:
        type: "array"
        items:
          $ref: "#/definitions/handlers.JWK"
    example:
      keys:
      - kty: "kty"
        e: "e"
        use: "use"
        kid: "kid"
        alg: "alg"
        "n": "n"
      - kty: "kty"
        e: "e"
        use: "use"
        kid: "kid"
        alg: "alg"
        "n": "n"
externalDocs:
  description: "OpenAPI"
  url: "https://swagger.io/resources/open-api/"
