/*
 * ichibuy/auth API
 *
 * This is the ichibuy/auth API.
 *
 * API version: 1.0
 * Contact: support@swagger.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type HandlersJwks struct {
	Keys []HandlersJwk `json:"keys,omitempty"`
}
