/*
 * ichibuy/auth API
 *
 * This is the ichibuy/auth API.
 *
 * API version: 1.0
 * Contact: support@swagger.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type HandlersJwk struct {
	Alg string `json:"alg,omitempty"`
	E string `json:"e,omitempty"`
	Kid string `json:"kid,omitempty"`
	Kty string `json:"kty,omitempty"`
	N string `json:"n,omitempty"`
	Use string `json:"use,omitempty"`
}
