/*
 * ichibuy/store API
 *
 * This is the ichibuy/store API.
 *
 * API version: 1.0
 * Contact: support@swagger.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ServicesStoreListItem struct {
	CreatedAt string `json:"created_at,omitempty"`
	Description string `json:"description,omitempty"`
	Id string `json:"id,omitempty"`
	Lat float32 `json:"lat,omitempty"`
	Lng float32 `json:"lng,omitempty"`
	Name string `json:"name,omitempty"`
	Slug string `json:"slug,omitempty"`
	UpdatedAt string `json:"updated_at,omitempty"`
	UserId string `json:"user_id,omitempty"`
}
