/*
 * ichibuy/store API
 *
 * This is the ichibuy/store API.
 *
 * API version: 1.0
 * Contact: support@swagger.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type HandlersUpdateCustomerBody struct {
	Email string `json:"email,omitempty"`
	FirstName string `json:"first_name"`
	LastName string `json:"last_name"`
	Phone string `json:"phone,omitempty"`
}
