/*
 * ichibuy/store API
 *
 * This is the ichibuy/store API.
 *
 * API version: 1.0
 * Contact: support@swagger.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Query struct {
	Query string `json:"query,omitempty"`
	Variables interface{} `json:"variables,omitempty"`
}
