/*
 * ichibuy/store API
 *
 * This is the ichibuy/store API.
 *
 * API version: 1.0
 * Contact: support@swagger.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ServicesPriceDto struct {
	// cents
	Amount int32 `json:"amount,omitempty"`
	Currency string `json:"currency,omitempty"`
	Id string `json:"id,omitempty"`
}
