/*
 * ichibuy/store API
 *
 * This is the ichibuy/store API.
 *
 * API version: 1.0
 * Contact: support@swagger.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ServicesGetCustomerResp struct {
	CreatedAt string `json:"created_at,omitempty"`
	Email string `json:"email,omitempty"`
	FirstName string `json:"first_name,omitempty"`
	Id string `json:"id,omitempty"`
	LastName string `json:"last_name,omitempty"`
	Phone string `json:"phone,omitempty"`
	UpdatedAt string `json:"updated_at,omitempty"`
	UserId string `json:"user_id,omitempty"`
}
