/*
 * ichibuy/store API
 *
 * This is the ichibuy/store API.
 *
 * API version: 1.0
 * Contact: support@swagger.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ServicesListProductsResp struct {
	Limit int32 `json:"limit,omitempty"`
	Offset int32 `json:"offset,omitempty"`
	Products []ServicesProductListItem `json:"products,omitempty"`
	Total int32 `json:"total,omitempty"`
}
