/*
 * ichibuy/store API
 *
 * This is the ichibuy/store API.
 *
 * API version: 1.0
 * Contact: support@swagger.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ServicesProductListItem struct {
	Active bool `json:"active,omitempty"`
	CreatedAt string `json:"created_at,omitempty"`
	Description string `json:"description,omitempty"`
	Id string `json:"id,omitempty"`
	Images []ServicesImageDto `json:"images,omitempty"`
	Name string `json:"name,omitempty"`
	Prices []ServicesPriceDto `json:"prices,omitempty"`
	StoreId string `json:"store_id,omitempty"`
	UpdatedAt string `json:"updated_at,omitempty"`
}
