-- +goose Up
-- USERS (minimal data + OAuth identifier)
CREATE TABLE users (
  id UUID PRIMARY KEY,                -- generated by app
  username TEXT,
  email TEXT UNIQUE
);

-- +goose Down
DROP TABLE IF EXISTS users;